# Site Settings

paginate:            5
disqus:              mitrov.github.io
twitter_username:    _dzmi

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:                [jekyll-paginate]
